server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # nocos服务地址
        server-addr: localhost:8848
        # 配置集群名称，也就是机房位置，例如：HZ，杭州
        cluster-name: HN
        # 命名空间，填ID
        namespace: 175844d6-8138-41b8-9b59-24aa6220918d
          #设置为非临时实例
#          ephemeral: false
    gateway:
      # 全局的跨域处理
      globalcors:
        # 解决options请求被拦截问题
        add-to-simple-url-handler-mapping: true
        # 允许哪些网站的跨域请求
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8090"
              - "http://www.leyou.com"
            # 允许的跨域ajax的请求方式
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "OPTIONS"
            # 允许在请求中携带的头信息
            allowedHeaders: "*"
            # 是否允许携带cookie
            allowCredentials: true
            # 这次跨域检测的有效期
            maxAge: 360000
      routes:
          # 路由标识。必须唯一
        - id: user-service
          # 路由的目标地址
          uri: lb://userservice
          # 路由断言，判断请求是否符合规则
          predicates:
            # 路径断言，判断路径是否是以/user开头，如果是则符合
            - Path=/user/**
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
#          filters:
#            - AddRequestHeader=Truth,Itcast is freaking awesome!
      default-filters:
        - AddRequestHeader=Truth,Itcast is freaking awesome!